CREATE TABLE USUARIOS_FACTUR(IDUSUARIO INT IDENTITY(1,1)PRIMARY KEY, USERNAME VARCHAR(200),DNI VARCHAR(10), EMAIL varchar(100), 
USUARIO VARCHAR(50),PASSWORD VARCHAR(MAX),CARGO VARCHAR(50),CANT_ACCESOS INT,RUC varchar(20), PROYECTO VARCHAR(30), STATUS INT,
FECHA_REGISTRO DATETIME)

CREATE TABLE BDLICENCIAS(IDLICENCIA INT IDENTITY(1,1)PRIMARY KEY,RUC varchar(20), EMAIL varchar(100),
FECHA_INICIO DATETIME, FECHA_FIN DATETIME, CANTUSER INT, STATUS INT, VALIDATE_EMAIL INT, FECHA_REGISTRO DATETIME, PROYECTO VARCHAR(30))